Fix compile warning about I2C_REG
Paciente8159/uCNC pull request #773
Opened 2024-11-09 20:51 UTC by ricochet1k

I2C_REG doesn't even look like the right name, and it's never defined to anything else, so just get rid of it and replace with Wire

Warning looked like this:
```
uCNC/src/hal/mcus/lpc176x/lpc176x_arduino.cpp:84: warning: "I2C_REG" redefined
   84 | #define I2C_REG Wire
      | 
In file included from uCNC/src/hal/mcus/lpc176x/../../../hal/boards/../mcus/mcudefs.h:57,
                 from uCNC/src/hal/mcus/lpc176x/../../../hal/boards/boarddefs.h:44,
                 from uCNC/src/hal/mcus/lpc176x/../../../cnc_hal_config_helper.h:49,
                 from uCNC/src/hal/mcus/lpc176x/../../../cnc.h:135,
                 from uCNC/src/hal/mcus/lpc176x/lpc176x_arduino.cpp:34:
uCNC/src/hal/mcus/lpc176x/../../../hal/boards/../mcus/lpc176x/mcumap_lpc176x.h:4558: note: this is the location of the previous definition
 4558 | #define I2C_REG __helper__(LPC_I2C, I2C_PORT, )
      | 
```

2024-11-09 22:47 UTC, Paciente8159 requested changes
Actually there is a better way to implement this.
Adding a `#undef I2C_REG` before the `#define I2C_REG Wire` would do the trick.

There is a reason why this was implemented like this. The LPC Arduino implementation is very basic and incomplete. But it would be possible to have multiple Wire instances since the LPC17xx supports up to 3 I2C drivers. It would be possible to have Wire Wire1 and Wire2 for example and then select the Wire instance to use with I2C_REG, although they never were implemented.

2024-11-09 23:35 UTC, ricochet1k commented
I mean you could #undef it, but I2C_REG doesn't seem like the right name anyway, especially since it's being used already. Something like I2C_WIRE or I2C_DRIVER?

2024-11-14 09:11 UTC, Paciente8159 commented
> I mean you could #undef it, but I2C_REG doesn't seem like the right name anyway, especially since it's being used already. Something like I2C_WIRE or I2C_DRIVER?

It's being used outside of the µCNC scope (at the framework level?)
If not reusing the I2C_REG makes more sense since this makes it transparent (for core code)

2024-11-20 16:16 UTC, Paciente8159 commented
Integrated via #783

2024-11-20 16:16 UTC, closed without merging